cmake_minimum_required(VERSION 3.14)
project(FetchTest)
include(FetchContent)
FetchContent_Declare(eigen URL https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz)
FetchContent_GetProperties(eigen)
if(NOT eigen_POPULATED)
    FetchContent_Populate(eigen)
endif()
add_executable(test main.cpp)
target_include_directories(test PRIVATE \)
